### ISSUE TITLE
Error after 3.5 install (CHCO)

### ISSUE THREAD

**Issue by accomer** [UCCC/CHORDS-QA#18]
I was able to run reports before I installed version 3.5 of the software.  After I have downloaded the required packages and try to run the P1 report, this is the error I am receiving:

> chordsTables::run_report("P1")
Error in tools::file_path_as_absolute(input) : file '' does not exist
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect

Can you let me know how to get past this?

Thanks
Angela

**Comment by vtmacox** [comment]
you will have to reinstall all the previous packages after you update to a new version of R.  Try installing the `chordsTables` package and this should fix the problem.

**Comment by accomer** [comment]
I am running into this error after installing the chordsTables package

**Comment by vtmacox** [comment]
I can't replicate this error and other people haven't had this problem either.  I think it might be an issue with your machine/R setup.  Try updating RStudio and all of your R packages.  I don't think the packages are problem though.  If that doesn't work, you might try doing a full uninstall of R and RStudio and retry installing both programs.  

Since this doesn't appear to be a problem with the package, I'm afraid I can't be of more help.
